//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 10:40:13 AM PST 
//


package com.macys.sdt.projects.Customer.OESBB.utils.input.price.error;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the main.java package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: main.java
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MailMessagePayload }
     * 
     */
    public QA409_28_MCOM createMailMessagePayload() {
        return new QA409_28_MCOM();
    }

    /**
     * Create an instance of {@link MailMessagePayload.BillingDetail }
     * 
     */
    public QA409_28_MCOM.BillingDetail createMailMessagePayloadBillingDetail() {
        return new QA409_28_MCOM.BillingDetail();
    }

}
