//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.17 at 08:07:59 PM PST 
//


package com.macys.sdt.projects.Customer.OESBB.utils.input.giftreturn.confirmation;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the main.java package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: main.java
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MailMessagePayload }
     * 
     */
    public QA244_2_MCOM createMailMessagePayload() {
        return new QA244_2_MCOM();
    }

    /**
     * Create an instance of {@link MailMessagePayload.ShipmentDetail }
     * 
     */
    public QA244_2_MCOM.ShipmentDetail createMailMessagePayloadShipmentDetail() {
        return new QA244_2_MCOM.ShipmentDetail();
    }

    /**
     * Create an instance of {@link MailMessagePayload.BillingDetail }
     * 
     */
    public QA244_2_MCOM.BillingDetail createMailMessagePayloadBillingDetail() {
        return new QA244_2_MCOM.BillingDetail();
    }

    /**
     * Create an instance of {@link MailMessagePayload.PaymentDetail }
     * 
     */
    public QA244_2_MCOM.PaymentDetail createMailMessagePayloadPaymentDetail() {
        return new QA244_2_MCOM.PaymentDetail();
    }

    /**
     * Create an instance of {@link MailMessagePayload.ShipmentDetail.ItemDetail }
     * 
     */
    public QA244_2_MCOM.ShipmentDetail.ItemDetail createMailMessagePayloadShipmentDetailItemDetail() {
        return new QA244_2_MCOM.ShipmentDetail.ItemDetail();
    }

}
