//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.05 at 12:49:29 PM PST 
//


package com.macys.sdt.projects.Customer.OESBB.utils.input.giftreturn.confirmation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reservationNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="internetOrderNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="orderDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="shopAt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="explanationText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="orderSubtotalAmt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="baseShippingAmt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="addtShipAddAmt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="shipUpgradeAmt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="giftWrapAmt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="taxAmt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="orderTotal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="divisionCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="locationCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="adhocText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phoneNbrCS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hoursCS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phoneNbrFP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hoursFP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="smsFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ltyFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ltyIdUsl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="billingDetail">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="middleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="attnLine" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="addressLine1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="addressLine2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="addressLine3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="zipcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="paymentDetail">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="paymentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="accountNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="paymentCategoryFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="egcCertificateType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="shipmentDetail">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="shipmentNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="shippedDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="mailFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="middleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="attnLine" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="addressLine1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="addressLine2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="addressLine3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="zipcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="greetingMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="closingMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="signatureMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="giftRegistryNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="giftWrapFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="giftReceipientEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="giftRegistrant1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="giftRegistrant2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="giftReceiptFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="pickupBarcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="pickupReadyDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="pickupCancelDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="shipRetailAmt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="shipTaxAmt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="shipFilLoc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="shipPhone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="shipEmailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="itemDetail">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="lineNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="requestedQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="availableQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="shippedQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="totalAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="expectedDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="newExpectedDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="delaySentDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="delayWaitDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="systemCancelDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="shipmentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="splitShipmentFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="vendor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="cancelledQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="upcId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="userCancelDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="vgcNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="vgcCidNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="expiryDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="color" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reservationNumber",
    "internetOrderNumber",
    "orderDate",
    "shopAt",
    "explanationText",
    "orderSubtotalAmt",
    "baseShippingAmt",
    "addtShipAddAmt",
    "shipUpgradeAmt",
    "giftWrapAmt",
    "taxAmt",
    "orderTotal",
    "divisionCode",
    "locationCode",
    "adhocText",
    "phoneNbrCS",
    "hoursCS",
    "phoneNbrFP",
    "hoursFP",
    "smsFlag",
    "ltyFlag",
    "ltyIdUsl",
    "billingDetail",
    "paymentDetail",
    "shipmentDetail"
})
@XmlRootElement(name = "mailMessagePayload")
public class QA244_2_MCOM {

    @XmlElement(required = true)
    protected String reservationNumber;
    @XmlElement(required = true)
    protected String internetOrderNumber;
    @XmlElement(required = true)
    protected String orderDate;
    @XmlElement(required = true)
    protected String shopAt;
    @XmlElement(required = true)
    protected String explanationText;
    @XmlElement(required = true)
    protected String orderSubtotalAmt;
    @XmlElement(required = true)
    protected String baseShippingAmt;
    @XmlElement(required = true)
    protected String addtShipAddAmt;
    @XmlElement(required = true)
    protected String shipUpgradeAmt;
    @XmlElement(required = true)
    protected String giftWrapAmt;
    @XmlElement(required = true)
    protected String taxAmt;
    @XmlElement(required = true)
    protected String orderTotal;
    @XmlElement(required = true)
    protected String divisionCode;
    @XmlElement(required = true)
    protected String locationCode;
    @XmlElement(required = true)
    protected String adhocText;
    @XmlElement(required = true)
    protected String phoneNbrCS;
    @XmlElement(required = true)
    protected String hoursCS;
    @XmlElement(required = true)
    protected String phoneNbrFP;
    @XmlElement(required = true)
    protected String hoursFP;
    @XmlElement(required = true)
    protected String smsFlag;
    @XmlElement(required = true)
    protected String ltyFlag;
    @XmlElement(required = true)
    protected String ltyIdUsl;
    @XmlElement(required = true)
    protected QA244_2_MCOM.BillingDetail billingDetail;
    @XmlElement(required = true)
    protected QA244_2_MCOM.PaymentDetail paymentDetail;
    @XmlElement(required = true)
    protected QA244_2_MCOM.ShipmentDetail shipmentDetail;

    /**
     * Gets the value of the reservationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReservationNumber() {
        return reservationNumber;
    }

    /**
     * Sets the value of the reservationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReservationNumber(String value) {
        this.reservationNumber = value;
    }

    /**
     * Gets the value of the internetOrderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternetOrderNumber() {
        return internetOrderNumber;
    }

    /**
     * Sets the value of the internetOrderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternetOrderNumber(String value) {
        this.internetOrderNumber = value;
    }

    /**
     * Gets the value of the orderDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderDate() {
        return orderDate;
    }

    /**
     * Sets the value of the orderDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderDate(String value) {
        this.orderDate = value;
    }

    /**
     * Gets the value of the shopAt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShopAt() {
        return shopAt;
    }

    /**
     * Sets the value of the shopAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShopAt(String value) {
        this.shopAt = value;
    }

    /**
     * Gets the value of the explanationText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExplanationText() {
        return explanationText;
    }

    /**
     * Sets the value of the explanationText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExplanationText(String value) {
        this.explanationText = value;
    }

    /**
     * Gets the value of the orderSubtotalAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderSubtotalAmt() {
        return orderSubtotalAmt;
    }

    /**
     * Sets the value of the orderSubtotalAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderSubtotalAmt(String value) {
        this.orderSubtotalAmt = value;
    }

    /**
     * Gets the value of the baseShippingAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseShippingAmt() {
        return baseShippingAmt;
    }

    /**
     * Sets the value of the baseShippingAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseShippingAmt(String value) {
        this.baseShippingAmt = value;
    }

    /**
     * Gets the value of the addtShipAddAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddtShipAddAmt() {
        return addtShipAddAmt;
    }

    /**
     * Sets the value of the addtShipAddAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddtShipAddAmt(String value) {
        this.addtShipAddAmt = value;
    }

    /**
     * Gets the value of the shipUpgradeAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipUpgradeAmt() {
        return shipUpgradeAmt;
    }

    /**
     * Sets the value of the shipUpgradeAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipUpgradeAmt(String value) {
        this.shipUpgradeAmt = value;
    }

    /**
     * Gets the value of the giftWrapAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGiftWrapAmt() {
        return giftWrapAmt;
    }

    /**
     * Sets the value of the giftWrapAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGiftWrapAmt(String value) {
        this.giftWrapAmt = value;
    }

    /**
     * Gets the value of the taxAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxAmt() {
        return taxAmt;
    }

    /**
     * Sets the value of the taxAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxAmt(String value) {
        this.taxAmt = value;
    }

    /**
     * Gets the value of the orderTotal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderTotal() {
        return orderTotal;
    }

    /**
     * Sets the value of the orderTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderTotal(String value) {
        this.orderTotal = value;
    }

    /**
     * Gets the value of the divisionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDivisionCode() {
        return divisionCode;
    }

    /**
     * Sets the value of the divisionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDivisionCode(String value) {
        this.divisionCode = value;
    }

    /**
     * Gets the value of the locationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationCode() {
        return locationCode;
    }

    /**
     * Sets the value of the locationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationCode(String value) {
        this.locationCode = value;
    }

    /**
     * Gets the value of the adhocText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdhocText() {
        return adhocText;
    }

    /**
     * Sets the value of the adhocText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdhocText(String value) {
        this.adhocText = value;
    }

    /**
     * Gets the value of the phoneNbrCS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneNbrCS() {
        return phoneNbrCS;
    }

    /**
     * Sets the value of the phoneNbrCS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneNbrCS(String value) {
        this.phoneNbrCS = value;
    }

    /**
     * Gets the value of the hoursCS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoursCS() {
        return hoursCS;
    }

    /**
     * Sets the value of the hoursCS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoursCS(String value) {
        this.hoursCS = value;
    }

    /**
     * Gets the value of the phoneNbrFP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneNbrFP() {
        return phoneNbrFP;
    }

    /**
     * Sets the value of the phoneNbrFP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneNbrFP(String value) {
        this.phoneNbrFP = value;
    }

    /**
     * Gets the value of the hoursFP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoursFP() {
        return hoursFP;
    }

    /**
     * Sets the value of the hoursFP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoursFP(String value) {
        this.hoursFP = value;
    }

    /**
     * Gets the value of the smsFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmsFlag() {
        return smsFlag;
    }

    /**
     * Sets the value of the smsFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmsFlag(String value) {
        this.smsFlag = value;
    }

    /**
     * Gets the value of the ltyFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLtyFlag() {
        return ltyFlag;
    }

    /**
     * Sets the value of the ltyFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLtyFlag(String value) {
        this.ltyFlag = value;
    }

    /**
     * Gets the value of the ltyIdUsl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLtyIdUsl() {
        return ltyIdUsl;
    }

    /**
     * Sets the value of the ltyIdUsl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLtyIdUsl(String value) {
        this.ltyIdUsl = value;
    }

    /**
     * Gets the value of the billingDetail property.
     * 
     * @return
     *     possible object is
     *     {@link QA244_2_MCOM.BillingDetail }
     *     
     */
    public QA244_2_MCOM.BillingDetail getBillingDetail() {
        return billingDetail;
    }

    /**
     * Sets the value of the billingDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link QA244_2_MCOM.BillingDetail }
     *     
     */
    public void setBillingDetail(QA244_2_MCOM.BillingDetail value) {
        this.billingDetail = value;
    }

    /**
     * Gets the value of the paymentDetail property.
     * 
     * @return
     *     possible object is
     *     {@link QA244_2_MCOM.PaymentDetail }
     *     
     */
    public QA244_2_MCOM.PaymentDetail getPaymentDetail() {
        return paymentDetail;
    }

    /**
     * Sets the value of the paymentDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link QA244_2_MCOM.PaymentDetail }
     *     
     */
    public void setPaymentDetail(QA244_2_MCOM.PaymentDetail value) {
        this.paymentDetail = value;
    }

    /**
     * Gets the value of the shipmentDetail property.
     * 
     * @return
     *     possible object is
     *     {@link QA244_2_MCOM.ShipmentDetail }
     *     
     */
    public QA244_2_MCOM.ShipmentDetail getShipmentDetail() {
        return shipmentDetail;
    }

    /**
     * Sets the value of the shipmentDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link QA244_2_MCOM.ShipmentDetail }
     *     
     */
    public void setShipmentDetail(QA244_2_MCOM.ShipmentDetail value) {
        this.shipmentDetail = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="middleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="attnLine" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="addressLine1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="addressLine2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="addressLine3" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="zipcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "title",
        "firstName",
        "middleName",
        "lastName",
        "attnLine",
        "addressLine1",
        "addressLine2",
        "addressLine3",
        "city",
        "state",
        "country",
        "zipcode"
    })
    public static class BillingDetail {

        @XmlElement(required = true)
        protected String title;
        @XmlElement(required = true)
        protected String firstName;
        @XmlElement(required = true)
        protected String middleName;
        @XmlElement(required = true)
        protected String lastName;
        @XmlElement(required = true)
        protected String attnLine;
        @XmlElement(required = true)
        protected String addressLine1;
        @XmlElement(required = true)
        protected String addressLine2;
        @XmlElement(required = true)
        protected String addressLine3;
        @XmlElement(required = true)
        protected String city;
        @XmlElement(required = true)
        protected String state;
        @XmlElement(required = true)
        protected String country;
        @XmlElement(required = true)
        protected String zipcode;

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the firstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirstName() {
            return firstName;
        }

        /**
         * Sets the value of the firstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirstName(String value) {
            this.firstName = value;
        }

        /**
         * Gets the value of the middleName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMiddleName() {
            return middleName;
        }

        /**
         * Sets the value of the middleName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMiddleName(String value) {
            this.middleName = value;
        }

        /**
         * Gets the value of the lastName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastName() {
            return lastName;
        }

        /**
         * Sets the value of the lastName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastName(String value) {
            this.lastName = value;
        }

        /**
         * Gets the value of the attnLine property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttnLine() {
            return attnLine;
        }

        /**
         * Sets the value of the attnLine property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttnLine(String value) {
            this.attnLine = value;
        }

        /**
         * Gets the value of the addressLine1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddressLine1() {
            return addressLine1;
        }

        /**
         * Sets the value of the addressLine1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddressLine1(String value) {
            this.addressLine1 = value;
        }

        /**
         * Gets the value of the addressLine2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddressLine2() {
            return addressLine2;
        }

        /**
         * Sets the value of the addressLine2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddressLine2(String value) {
            this.addressLine2 = value;
        }

        /**
         * Gets the value of the addressLine3 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddressLine3() {
            return addressLine3;
        }

        /**
         * Sets the value of the addressLine3 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddressLine3(String value) {
            this.addressLine3 = value;
        }

        /**
         * Gets the value of the city property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCity() {
            return city;
        }

        /**
         * Sets the value of the city property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCity(String value) {
            this.city = value;
        }

        /**
         * Gets the value of the state property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getState() {
            return state;
        }

        /**
         * Sets the value of the state property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setState(String value) {
            this.state = value;
        }

        /**
         * Gets the value of the country property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountry() {
            return country;
        }

        /**
         * Sets the value of the country property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountry(String value) {
            this.country = value;
        }

        /**
         * Gets the value of the zipcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZipcode() {
            return zipcode;
        }

        /**
         * Sets the value of the zipcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZipcode(String value) {
            this.zipcode = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="paymentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="accountNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="paymentCategoryFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="egcCertificateType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "paymentType",
        "accountNumber",
        "amount",
        "paymentCategoryFlag",
        "egcCertificateType"
    })
    public static class PaymentDetail {

        @XmlElement(required = true)
        protected String paymentType;
        @XmlElement(required = true)
        protected String accountNumber;
        @XmlElement(required = true)
        protected String amount;
        @XmlElement(required = true)
        protected String paymentCategoryFlag;
        @XmlElement(required = true)
        protected String egcCertificateType;

        /**
         * Gets the value of the paymentType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPaymentType() {
            return paymentType;
        }

        /**
         * Sets the value of the paymentType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPaymentType(String value) {
            this.paymentType = value;
        }

        /**
         * Gets the value of the accountNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccountNumber() {
            return accountNumber;
        }

        /**
         * Sets the value of the accountNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccountNumber(String value) {
            this.accountNumber = value;
        }

        /**
         * Gets the value of the amount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAmount(String value) {
            this.amount = value;
        }

        /**
         * Gets the value of the paymentCategoryFlag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPaymentCategoryFlag() {
            return paymentCategoryFlag;
        }

        /**
         * Sets the value of the paymentCategoryFlag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPaymentCategoryFlag(String value) {
            this.paymentCategoryFlag = value;
        }

        /**
         * Gets the value of the egcCertificateType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEgcCertificateType() {
            return egcCertificateType;
        }

        /**
         * Sets the value of the egcCertificateType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEgcCertificateType(String value) {
            this.egcCertificateType = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="shipmentNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="shippedDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="mailFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="middleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="attnLine" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="addressLine1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="addressLine2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="addressLine3" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="zipcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="greetingMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="closingMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="signatureMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="giftRegistryNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="giftWrapFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="giftReceipientEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="giftRegistrant1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="giftRegistrant2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="giftReceiptFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="pickupBarcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="pickupReadyDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="pickupCancelDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="shipRetailAmt" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="shipTaxAmt" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="shipFilLoc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="shipPhone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="shipEmailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="itemDetail">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="lineNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="requestedQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="availableQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="shippedQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="totalAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="expectedDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="newExpectedDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="delaySentDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="delayWaitDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="systemCancelDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="shipmentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="splitShipmentFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="vendor" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="cancelledQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="upcId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="userCancelDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="vgcNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="vgcCidNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="expiryDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="color" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "shipmentNumber",
        "shippedDate",
        "mailFlag",
        "title",
        "firstName",
        "middleName",
        "lastName",
        "attnLine",
        "addressLine1",
        "addressLine2",
        "addressLine3",
        "city",
        "state",
        "country",
        "zipcode",
        "greetingMessage",
        "closingMessage",
        "signatureMessage",
        "giftRegistryNumber",
        "giftWrapFlag",
        "giftReceipientEmail",
        "giftRegistrant1",
        "giftRegistrant2",
        "giftReceiptFlag",
        "pickupBarcode",
        "pickupReadyDate",
        "pickupCancelDate",
        "shipRetailAmt",
        "shipTaxAmt",
        "shipFilLoc",
        "shipPhone",
        "shipEmailAddress",
        "itemDetail"
    })
    public static class ShipmentDetail {

        @XmlElement(required = true)
        protected String shipmentNumber;
        @XmlElement(required = true)
        protected String shippedDate;
        @XmlElement(required = true)
        protected String mailFlag;
        @XmlElement(required = true)
        protected String title;
        @XmlElement(required = true)
        protected String firstName;
        @XmlElement(required = true)
        protected String middleName;
        @XmlElement(required = true)
        protected String lastName;
        @XmlElement(required = true)
        protected String attnLine;
        @XmlElement(required = true)
        protected String addressLine1;
        @XmlElement(required = true)
        protected String addressLine2;
        @XmlElement(required = true)
        protected String addressLine3;
        @XmlElement(required = true)
        protected String city;
        @XmlElement(required = true)
        protected String state;
        @XmlElement(required = true)
        protected String country;
        @XmlElement(required = true)
        protected String zipcode;
        @XmlElement(required = true)
        protected String greetingMessage;
        @XmlElement(required = true)
        protected String closingMessage;
        @XmlElement(required = true)
        protected String signatureMessage;
        @XmlElement(required = true)
        protected String giftRegistryNumber;
        @XmlElement(required = true)
        protected String giftWrapFlag;
        @XmlElement(required = true)
        protected String giftReceipientEmail;
        @XmlElement(required = true)
        protected String giftRegistrant1;
        @XmlElement(required = true)
        protected String giftRegistrant2;
        @XmlElement(required = true)
        protected String giftReceiptFlag;
        @XmlElement(required = true)
        protected String pickupBarcode;
        @XmlElement(required = true)
        protected String pickupReadyDate;
        @XmlElement(required = true)
        protected String pickupCancelDate;
        @XmlElement(required = true)
        protected String shipRetailAmt;
        @XmlElement(required = true)
        protected String shipTaxAmt;
        @XmlElement(required = true)
        protected String shipFilLoc;
        @XmlElement(required = true)
        protected String shipPhone;
        @XmlElement(required = true)
        protected String shipEmailAddress;
        @XmlElement(required = true)
        protected QA244_2_MCOM.ShipmentDetail.ItemDetail itemDetail;

        /**
         * Gets the value of the shipmentNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShipmentNumber() {
            return shipmentNumber;
        }

        /**
         * Sets the value of the shipmentNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShipmentNumber(String value) {
            this.shipmentNumber = value;
        }

        /**
         * Gets the value of the shippedDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShippedDate() {
            return shippedDate;
        }

        /**
         * Sets the value of the shippedDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShippedDate(String value) {
            this.shippedDate = value;
        }

        /**
         * Gets the value of the mailFlag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMailFlag() {
            return mailFlag;
        }

        /**
         * Sets the value of the mailFlag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMailFlag(String value) {
            this.mailFlag = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the firstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirstName() {
            return firstName;
        }

        /**
         * Sets the value of the firstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirstName(String value) {
            this.firstName = value;
        }

        /**
         * Gets the value of the middleName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMiddleName() {
            return middleName;
        }

        /**
         * Sets the value of the middleName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMiddleName(String value) {
            this.middleName = value;
        }

        /**
         * Gets the value of the lastName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastName() {
            return lastName;
        }

        /**
         * Sets the value of the lastName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastName(String value) {
            this.lastName = value;
        }

        /**
         * Gets the value of the attnLine property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttnLine() {
            return attnLine;
        }

        /**
         * Sets the value of the attnLine property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttnLine(String value) {
            this.attnLine = value;
        }

        /**
         * Gets the value of the addressLine1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddressLine1() {
            return addressLine1;
        }

        /**
         * Sets the value of the addressLine1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddressLine1(String value) {
            this.addressLine1 = value;
        }

        /**
         * Gets the value of the addressLine2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddressLine2() {
            return addressLine2;
        }

        /**
         * Sets the value of the addressLine2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddressLine2(String value) {
            this.addressLine2 = value;
        }

        /**
         * Gets the value of the addressLine3 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddressLine3() {
            return addressLine3;
        }

        /**
         * Sets the value of the addressLine3 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddressLine3(String value) {
            this.addressLine3 = value;
        }

        /**
         * Gets the value of the city property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCity() {
            return city;
        }

        /**
         * Sets the value of the city property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCity(String value) {
            this.city = value;
        }

        /**
         * Gets the value of the state property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getState() {
            return state;
        }

        /**
         * Sets the value of the state property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setState(String value) {
            this.state = value;
        }

        /**
         * Gets the value of the country property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountry() {
            return country;
        }

        /**
         * Sets the value of the country property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountry(String value) {
            this.country = value;
        }

        /**
         * Gets the value of the zipcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZipcode() {
            return zipcode;
        }

        /**
         * Sets the value of the zipcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZipcode(String value) {
            this.zipcode = value;
        }

        /**
         * Gets the value of the greetingMessage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGreetingMessage() {
            return greetingMessage;
        }

        /**
         * Sets the value of the greetingMessage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGreetingMessage(String value) {
            this.greetingMessage = value;
        }

        /**
         * Gets the value of the closingMessage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClosingMessage() {
            return closingMessage;
        }

        /**
         * Sets the value of the closingMessage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClosingMessage(String value) {
            this.closingMessage = value;
        }

        /**
         * Gets the value of the signatureMessage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSignatureMessage() {
            return signatureMessage;
        }

        /**
         * Sets the value of the signatureMessage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSignatureMessage(String value) {
            this.signatureMessage = value;
        }

        /**
         * Gets the value of the giftRegistryNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGiftRegistryNumber() {
            return giftRegistryNumber;
        }

        /**
         * Sets the value of the giftRegistryNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGiftRegistryNumber(String value) {
            this.giftRegistryNumber = value;
        }

        /**
         * Gets the value of the giftWrapFlag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGiftWrapFlag() {
            return giftWrapFlag;
        }

        /**
         * Sets the value of the giftWrapFlag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGiftWrapFlag(String value) {
            this.giftWrapFlag = value;
        }

        /**
         * Gets the value of the giftReceipientEmail property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGiftReceipientEmail() {
            return giftReceipientEmail;
        }

        /**
         * Sets the value of the giftReceipientEmail property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGiftReceipientEmail(String value) {
            this.giftReceipientEmail = value;
        }

        /**
         * Gets the value of the giftRegistrant1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGiftRegistrant1() {
            return giftRegistrant1;
        }

        /**
         * Sets the value of the giftRegistrant1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGiftRegistrant1(String value) {
            this.giftRegistrant1 = value;
        }

        /**
         * Gets the value of the giftRegistrant2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGiftRegistrant2() {
            return giftRegistrant2;
        }

        /**
         * Sets the value of the giftRegistrant2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGiftRegistrant2(String value) {
            this.giftRegistrant2 = value;
        }

        /**
         * Gets the value of the giftReceiptFlag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGiftReceiptFlag() {
            return giftReceiptFlag;
        }

        /**
         * Sets the value of the giftReceiptFlag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGiftReceiptFlag(String value) {
            this.giftReceiptFlag = value;
        }

        /**
         * Gets the value of the pickupBarcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPickupBarcode() {
            return pickupBarcode;
        }

        /**
         * Sets the value of the pickupBarcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPickupBarcode(String value) {
            this.pickupBarcode = value;
        }

        /**
         * Gets the value of the pickupReadyDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPickupReadyDate() {
            return pickupReadyDate;
        }

        /**
         * Sets the value of the pickupReadyDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPickupReadyDate(String value) {
            this.pickupReadyDate = value;
        }

        /**
         * Gets the value of the pickupCancelDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPickupCancelDate() {
            return pickupCancelDate;
        }

        /**
         * Sets the value of the pickupCancelDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPickupCancelDate(String value) {
            this.pickupCancelDate = value;
        }

        /**
         * Gets the value of the shipRetailAmt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShipRetailAmt() {
            return shipRetailAmt;
        }

        /**
         * Sets the value of the shipRetailAmt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShipRetailAmt(String value) {
            this.shipRetailAmt = value;
        }

        /**
         * Gets the value of the shipTaxAmt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShipTaxAmt() {
            return shipTaxAmt;
        }

        /**
         * Sets the value of the shipTaxAmt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShipTaxAmt(String value) {
            this.shipTaxAmt = value;
        }

        /**
         * Gets the value of the shipFilLoc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShipFilLoc() {
            return shipFilLoc;
        }

        /**
         * Sets the value of the shipFilLoc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShipFilLoc(String value) {
            this.shipFilLoc = value;
        }

        /**
         * Gets the value of the shipPhone property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShipPhone() {
            return shipPhone;
        }

        /**
         * Sets the value of the shipPhone property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShipPhone(String value) {
            this.shipPhone = value;
        }

        /**
         * Gets the value of the shipEmailAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShipEmailAddress() {
            return shipEmailAddress;
        }

        /**
         * Sets the value of the shipEmailAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShipEmailAddress(String value) {
            this.shipEmailAddress = value;
        }

        /**
         * Gets the value of the itemDetail property.
         * 
         * @return
         *     possible object is
         *     {@link QA244_2_MCOM.ShipmentDetail.ItemDetail }
         *     
         */
        public QA244_2_MCOM.ShipmentDetail.ItemDetail getItemDetail() {
            return itemDetail;
        }

        /**
         * Sets the value of the itemDetail property.
         * 
         * @param value
         *     allowed object is
         *     {@link QA244_2_MCOM.ShipmentDetail.ItemDetail }
         *     
         */
        public void setItemDetail(QA244_2_MCOM.ShipmentDetail.ItemDetail value) {
            this.itemDetail = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="lineNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="requestedQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="availableQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="shippedQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="totalAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="expectedDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="newExpectedDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="delaySentDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="delayWaitDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="systemCancelDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="shipmentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="splitShipmentFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="vendor" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="cancelledQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="upcId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="userCancelDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="vgcNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="vgcCidNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="expiryDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="color" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "lineNumber",
            "description",
            "price",
            "requestedQuantity",
            "availableQuantity",
            "shippedQuantity",
            "totalAmount",
            "expectedDate",
            "newExpectedDate",
            "delaySentDate",
            "delayWaitDate",
            "systemCancelDate",
            "shipmentType",
            "splitShipmentFlag",
            "status",
            "vendor",
            "cancelledQuantity",
            "upcId",
            "userCancelDate",
            "vgcNumber",
            "vgcCidNumber",
            "expiryDate",
            "size",
            "color"
        })
        public static class ItemDetail {

            @XmlElement(required = true)
            protected String lineNumber;
            @XmlElement(required = true)
            protected String description;
            @XmlElement(required = true)
            protected String price;
            @XmlElement(required = true)
            protected String requestedQuantity;
            @XmlElement(required = true)
            protected String availableQuantity;
            @XmlElement(required = true)
            protected String shippedQuantity;
            @XmlElement(required = true)
            protected String totalAmount;
            @XmlElement(required = true)
            protected String expectedDate;
            @XmlElement(required = true)
            protected String newExpectedDate;
            @XmlElement(required = true)
            protected String delaySentDate;
            @XmlElement(required = true)
            protected String delayWaitDate;
            @XmlElement(required = true)
            protected String systemCancelDate;
            @XmlElement(required = true)
            protected String shipmentType;
            @XmlElement(required = true)
            protected String splitShipmentFlag;
            @XmlElement(required = true)
            protected String status;
            @XmlElement(required = true)
            protected String vendor;
            @XmlElement(required = true)
            protected String cancelledQuantity;
            @XmlElement(required = true)
            protected String upcId;
            @XmlElement(required = true)
            protected String userCancelDate;
            @XmlElement(required = true)
            protected String vgcNumber;
            @XmlElement(required = true)
            protected String vgcCidNumber;
            @XmlElement(required = true)
            protected String expiryDate;
            @XmlElement(required = true)
            protected String size;
            @XmlElement(required = true)
            protected String color;

            /**
             * Gets the value of the lineNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLineNumber() {
                return lineNumber;
            }

            /**
             * Sets the value of the lineNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLineNumber(String value) {
                this.lineNumber = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the price property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrice() {
                return price;
            }

            /**
             * Sets the value of the price property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrice(String value) {
                this.price = value;
            }

            /**
             * Gets the value of the requestedQuantity property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequestedQuantity() {
                return requestedQuantity;
            }

            /**
             * Sets the value of the requestedQuantity property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequestedQuantity(String value) {
                this.requestedQuantity = value;
            }

            /**
             * Gets the value of the availableQuantity property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAvailableQuantity() {
                return availableQuantity;
            }

            /**
             * Sets the value of the availableQuantity property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAvailableQuantity(String value) {
                this.availableQuantity = value;
            }

            /**
             * Gets the value of the shippedQuantity property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getShippedQuantity() {
                return shippedQuantity;
            }

            /**
             * Sets the value of the shippedQuantity property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setShippedQuantity(String value) {
                this.shippedQuantity = value;
            }

            /**
             * Gets the value of the totalAmount property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTotalAmount() {
                return totalAmount;
            }

            /**
             * Sets the value of the totalAmount property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTotalAmount(String value) {
                this.totalAmount = value;
            }

            /**
             * Gets the value of the expectedDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExpectedDate() {
                return expectedDate;
            }

            /**
             * Sets the value of the expectedDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExpectedDate(String value) {
                this.expectedDate = value;
            }

            /**
             * Gets the value of the newExpectedDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNewExpectedDate() {
                return newExpectedDate;
            }

            /**
             * Sets the value of the newExpectedDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNewExpectedDate(String value) {
                this.newExpectedDate = value;
            }

            /**
             * Gets the value of the delaySentDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDelaySentDate() {
                return delaySentDate;
            }

            /**
             * Sets the value of the delaySentDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDelaySentDate(String value) {
                this.delaySentDate = value;
            }

            /**
             * Gets the value of the delayWaitDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDelayWaitDate() {
                return delayWaitDate;
            }

            /**
             * Sets the value of the delayWaitDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDelayWaitDate(String value) {
                this.delayWaitDate = value;
            }

            /**
             * Gets the value of the systemCancelDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSystemCancelDate() {
                return systemCancelDate;
            }

            /**
             * Sets the value of the systemCancelDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSystemCancelDate(String value) {
                this.systemCancelDate = value;
            }

            /**
             * Gets the value of the shipmentType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getShipmentType() {
                return shipmentType;
            }

            /**
             * Sets the value of the shipmentType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setShipmentType(String value) {
                this.shipmentType = value;
            }

            /**
             * Gets the value of the splitShipmentFlag property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSplitShipmentFlag() {
                return splitShipmentFlag;
            }

            /**
             * Sets the value of the splitShipmentFlag property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSplitShipmentFlag(String value) {
                this.splitShipmentFlag = value;
            }

            /**
             * Gets the value of the status property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStatus() {
                return status;
            }

            /**
             * Sets the value of the status property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStatus(String value) {
                this.status = value;
            }

            /**
             * Gets the value of the vendor property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVendor() {
                return vendor;
            }

            /**
             * Sets the value of the vendor property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVendor(String value) {
                this.vendor = value;
            }

            /**
             * Gets the value of the cancelledQuantity property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCancelledQuantity() {
                return cancelledQuantity;
            }

            /**
             * Sets the value of the cancelledQuantity property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCancelledQuantity(String value) {
                this.cancelledQuantity = value;
            }

            /**
             * Gets the value of the upcId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUpcId() {
                return upcId;
            }

            /**
             * Sets the value of the upcId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUpcId(String value) {
                this.upcId = value;
            }

            /**
             * Gets the value of the userCancelDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUserCancelDate() {
                return userCancelDate;
            }

            /**
             * Sets the value of the userCancelDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUserCancelDate(String value) {
                this.userCancelDate = value;
            }

            /**
             * Gets the value of the vgcNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVgcNumber() {
                return vgcNumber;
            }

            /**
             * Sets the value of the vgcNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVgcNumber(String value) {
                this.vgcNumber = value;
            }

            /**
             * Gets the value of the vgcCidNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVgcCidNumber() {
                return vgcCidNumber;
            }

            /**
             * Sets the value of the vgcCidNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVgcCidNumber(String value) {
                this.vgcCidNumber = value;
            }

            /**
             * Gets the value of the expiryDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExpiryDate() {
                return expiryDate;
            }

            /**
             * Sets the value of the expiryDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExpiryDate(String value) {
                this.expiryDate = value;
            }

            /**
             * Gets the value of the size property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSize() {
                return size;
            }

            /**
             * Sets the value of the size property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSize(String value) {
                this.size = value;
            }

            /**
             * Gets the value of the color property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getColor() {
                return color;
            }

            /**
             * Sets the value of the color property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setColor(String value) {
                this.color = value;
            }

        }

    }

}
