//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.29 at 04:20:33 PM PST 
//


package com.macys.sdt.projects.Customer.OESBB.utils.input.orderadjustment;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the main.java package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: main.java
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OA541_2_MCOM }
     * 
     */
    public QA541_2_241_2_MCOM createOA541_2_MCOM() {
        return new QA541_2_241_2_MCOM();
    }

    /**
     * Create an instance of {@link OA541_2_MCOM.ShipmentDetail }
     * 
     */
    public QA541_2_241_2_MCOM.ShipmentDetail createOA541_2_MCOMShipmentDetail() {
        return new QA541_2_241_2_MCOM.ShipmentDetail();
    }

    /**
     * Create an instance of {@link OA541_2_MCOM.BillingDetail }
     * 
     */
    public QA541_2_241_2_MCOM.BillingDetail createOA541_2_MCOMBillingDetail() {
        return new QA541_2_241_2_MCOM.BillingDetail();
    }

    /**
     * Create an instance of {@link OA541_2_MCOM.PaymentDetail }
     * 
     */
    public QA541_2_241_2_MCOM.PaymentDetail createOA541_2_MCOMPaymentDetail() {
        return new QA541_2_241_2_MCOM.PaymentDetail();
    }

    /**
     * Create an instance of {@link OA541_2_MCOM.ShipmentDetail.TrackingDetail }
     * 
     */
    public QA541_2_241_2_MCOM.ShipmentDetail.TrackingDetail createOA541_2_MCOMShipmentDetailTrackingDetail() {
        return new QA541_2_241_2_MCOM.ShipmentDetail.TrackingDetail();
    }

    /**
     * Create an instance of {@link OA541_2_MCOM.ShipmentDetail.ItemDetail }
     * 
     */
    public QA541_2_241_2_MCOM.ShipmentDetail.ItemDetail createOA541_2_MCOMShipmentDetailItemDetail() {
        return new QA541_2_241_2_MCOM.ShipmentDetail.ItemDetail();
    }

}
