# Author: Stat Team
# Story: SPR-51  - PR Service (based on MSP-Core)
# Date Created: 11/06/2017
# Date Signed Off:

@STAT @Manual @pending_returns @SPR-51
Feature: As an application I want to be able to process a Pending Transaction request so I can facilitate
  the creation and capture of a Pending Return.  (X-Macys-RequestId, trackingNbr, and confNbr are unique)

  @Macy's
  Scenario: QE to verify pendingTransId is generated with valid X-Macys-ClientId
    Given I am in Postman
    When I submit a PendingReturn with a valid X-Macys-ClientId
    Then I can see pendingTransId
    When I go to GEMS
    Then  I can see Pending ID generated by DCR and posted to the topic

  Scenario: QE to verify pendingTransId is not created with invalid X-Macys-CliendId
    Given I am in Postman
    When I submit a PendingReturn with an invalid X-Macys-CliendId
    Then I can see a validation error returned

  Scenario: QE to verify pendingTransId is not generated with duplicate RequestId
    Given I am in Postman
    When I submit a PendingReturn with a duplicate RequestId
    Then I can see a validation error returned

  Scenario: QE to verify pendingTransId is not created with Null rtnToAddressInfo
    Given I am in Postman
    When I submit a PendingReturn with null rtnToAddressInfo
    Then I can see a validation error returned for each required field

  Scenario: QE to verify pendingTransId is not created Null rtnToAddressInfoaddrLine1
    Given I am in Postman
    When I submit a PendingReturn with a null rtnToAddressInfoaddrLine1
    Then I can see a validation error returned for addrLine1

  Scenario: QE to verify address stored in database table ADDRESS_INFO column ADDR_LINE1
    Given I am in Postman
    When I submit a PendingReturn with a valid rtnToAddressInfo and pickupInfo
    Then I can see pendingTransId
    When I go to SQL Developer
    And I perform a Select on the pendingTransID in ADDRESS_INFO table
    Then I can see 2 rows with the pendingTransID in column PT_ID
    And I can see 0 in column ADDR_TYPE
    And I can see rtnToAddressInfo in column ADDR_LINE1
    And I can see 1 in column ADDR_TYPE
    And I can see pickupInfo in column ADDR_LINE1
    When I go to GEMS
    Then  I can see Pending ID generated by DCR and posted to the topic

  Scenario: QE to verify pendingTransId is generated without any rtnToAddressInfo
    Given I am in Postman
    When I submit a PendingReturn without any rtnToAddressInfo
    Then I can see pendingTransId
    When I go to SQL Developer
    And I perform a Select on the pendingTransID in ADDRESS_INFO table
    Then  I can see the pendingTransID is not in the table

  Scenario: QE to verify customerInfo in Pending request and pickupInfo is stored in CUSTOMER_INFO table
   with the correct value in CUST_TYPE
    Given I am in Postman
    When I submit a PendingReturn with customerInfo in Pending request and pickup
    Then I can see pendingTransId
    When I go to SQL Developer
    And I perform a Select on the pendingTransID in CUSTOMER_INFO table
    Then I can see 2 rows with the pendingTransID in column PT_ID
    And I can see 0 in column CUST_TYPE
    And I can see Pending request customerInfo in FIRST_NAME LAST_NAME EMAIL PHONE_NBR columns
    And I can see 1 in column CUST_TYPE
    And I can see pickup customerInfo in FIRST_NAME LAST_NAME EMAIL PHONE_NBR columns
    When I go to GEMS
    Then I can see Pending ID generated by DCR and posted to the topic


  Scenario: QE to verify pendingTransId is generated without any customerInfo in Pending request or pickup info
    Given I am in Postman
    When I submit a PendingReturn without customerInfo in Pending request or pickup
    Then I can see pendingTransId
    When I go to SQL Developer
    And I perform a Select on the pendingTransID in CUSTOMER_INFO table
    Then I can see pendingTransID is not in the table

  Scenario: QE to verify carrierInfo in Pending request is stored in CARRIER_INFO table
    Given I am in Postman
    When I submit a PendingReturn with carrierInfo
    Then I can see pendingTransId
    When I go to SQL Developer
    And I perform a Select on the pendingTransID in CARRIER_INFO table
    Then I can see carrierInfo in CARRIER_INFO table
    When I go to GEMS
    Then I can see Pending ID generated by DCR and posted to the topic

  Scenario: QE to verify pendingTransId is not created when carrierInfo is empty
    Given I am in Postman
    When I submit a PendingReturn with empty carrierInfo
    Then I can see a validation error returned for each required field

  Scenario: QE to verify pendingTransId is not created when schedDeliveryDate in carrierInfo is the wrong length
    Given I am in Postman
    When I submit a PendingReturn with schedDeliveryDate with a length of 9
    Then I can see a validation error returned for schedDeliveryDate

  Scenario: QE to verify pendingTransId is not created when acctNbr in carrierInfo is null
    Given I am in Postman
    When I submit a PendingReturn with null acctNbr
    Then I can see a validation error returned for acctNbr

  Scenario: QE to verify Pending request with different dates on PENDING_TRANS_ID table
    Given I am in Postman
    When I submit multiple PendingReturn on different days
    Then I can see pendingTransId
    When I go to SQL Developer
    And I perform a Select on the pentingTransId in PENDING_TRANS_ID table
    Then I can see pendingTransIDs for different days in the PT_ID column

  Scenario: QE to verify Pending request is stored in PENDING_TRANS table
    Given I am in Postman
    When I submit a PendingReturn
    Then I can see pendingTransId
    When I go to SQL Developer
    And I perform a Select on the pendingTransId in PENDING_TRANS table
    Then I can see the pending request info in PENDING_TRANS table
    When I go to GEMS
    Then I can see Pending ID generated by DCR and posted to the topic

  Scenario: QE to verify pendingTransId is not created without lineItemList
    Given I am in Postman
    When I submit a PendingReturn without lineItemList
    Then I can see a validation error returned for lineItemList

  Scenario: QE to verify mulitple items in one lineItemList are stored in PENDING_ITEMS table
    Given I am in Postman
    When I submit a PendingReturn with multiple items
    Then I can see pendingTransId
    When I go to SQL Developer
    And I perform a Select on the pendingTransID in PENDING_ITEMS table
    Then I can see a row for each item in PENDING_ITEMS table
    When I go to GEMS
    Then I can see Pending ID generated by DCR and posted to the topic

  Scenario: QE to verify pickupInfo in Pending request is stored in PICKUP_INFO table
    Given I am in Postman
    When I submit a PendingReturn with pickupInfo
    Then I can see pendingTransId
    When I go to SQL Developer
    And I perform a Select on the pendingTransID in PICKUP_INFO table
    Then I can see pickupInfo in PICKUP_INFO table
    When I go to GEMS
    Then  I can see Pending ID generated by DCR and posted to the topic

  Scenario: QE to verify pendingTransId is not created when pickupInfo is empty
    Given I am in Postman
    When I submit a PendingReturn with empty pickupInfo
    Then I can see a validation error returned for each required field

  Scenario: QE to verify pendingTransId is not created with invalid email in customerInfo
    Given I am in Postman
    When I submit a PendingReturn with an invalid email
    Then I can see a validation error returned for email








