# Author: Stat Team
# Story: SPR-209  - Alter Service (msp-pendingreturn-service)
# Date Created: 11/03/2017
# Date Signed Off:

@STAT @Manual @pending_returns @SPR-209
Feature: As an application I want to alter the service to reflect the changes made to the ORDER_NBR and RESERVATION_NBR
  columns on PENDING_TRANS so I can accurately capture/create a pending return.

@Macy's
Scenario: QE to verify pendingTransId is not created when orderNbr is greater than 30
  characters
  Given I am in Postman
  When I submit a PendingReturn with orderNbr length greater than 30
  Then I can see a validation error returned for orderNbr

  Scenario: QE to verify pendingTransID created when orderNbr less than 30 alphanumeric characters
    Given I am in Postman
    When I submit a PendingReturn with a valid orderNbr
    Then I can see pendingTransId
    When I go to SQL Developer
    And I perform a Select on the pendingTransID in PENDING_TRANS_ID table
    Then I can see pendingTransID in column PT_ID
    And I can see orderNbr in column ORDER_NBR
    When I perform a Select on the pendingTransID in PENDING_TRANS table
    Then I can see pendingTransID in column PT_ID
    And I can see orderNbr in column ORDER_NBR
    And I can see orderDate in column ORDER_DATE
    When I perform a Select on the pendingTransID in PENDING_ITEMS table
    Then I can see a row for each item in the PENDING_ITEMS table
    And I can see orderNbr in column ORDER_NBR
    And I can see orderDate in column ORDER_DATE
    When I go to GEMS
    Then  I can see Pending ID generated by DCR and posted to the topic

  Scenario: QE to verify when I post a pending return pendingTransId is not created when reservationNbr is greater
    than 100  characters
    Given I am in Postman
    When I submit a PendingReturn with reservationNbr length greater than 100
    Then I can see a validation error returned for reservationNbr

  Scenario: QE to verify pendingTransID created when reservationNbr less than 100 alphanumeric characters
    Given I am in Postman
    When I submit a PendingReturn with a valid reservationNbr
    Then I can see pendingTransId
    When I go to SQL Developer
    And I perform a Select on the pendingTransID in PENDING_TRANS_ID table
    Then I can see pendingTransID in column PT_ID
    And I can see reservationNbr in column RESERVATION_NBR
    When I perform a Select on the pendingTransID in PENDING_TRANS table
    Then I can see pendingTransID in column PT_ID
    And I can see reservationNbr in column RESERVATION_NBR
    When I perform a Select on the pendingTransID in PENDING_ITEMS table
    Then I can see a row for each item in the PENDING_ITEMS table
    And I can see reservationNbr in column RESERVATION_NBR
    When I go to GEMS
    Then  I can see Pending ID generated by DCR and posted to the topic

  Scenario: QE to verify pendingTransID created when pickupInfo.feeAmt is negative
    Given I am in Postman
    When I submit a PendingReturn with a negative pickupInfo.feeAmt
    Then I can see pendingTransId
    When I go to SQL Developer
    And I perform a Select on the pendingTransID in PICKUP_INFO table
    Then I can see pendingTransID in column PT_ID
    And I can see pickupInfo.feeAmt in column FEE_AMT
    When I go to GEMS
    Then  I can see Pending ID generated by DCR and posted to the topic

   Scenario: QE to verify pendingTransId is generated with X-Macys-ClientId = 01
    Given I am in Postman
    When I submit a PendingReturn with X-Macys-ClientId = 01
    Then I can see pendingTransId
    When I go to GEMS
    Then I can see Pending ID generated by DCR and posted to the topic

  Scenario: QE to verify pendingTransId is generated with X-Macys-ClientId = 02
    Given I am in Postman
    When I submit a PendingReturn with X-Macys-ClientId = 02
    Then I can see pendingTransId
    When I go to GEMS
    Then  I can see Pending ID generated by DCR and posted to the topic

  Scenario: QE to verify pendingTransId is generated with X-Macys-ClientId = 03
    Given I am in Postman
    When I submit a PendingReturn with X-Macys-ClientId = 03
    Then I can see pendingTransId
    When I go to GEMS
    Then  I can see Pending ID generated by DCR and posted to the topic

  Scenario: QE to verify pendingTransId is generated without pickupInfo
    Given I am in Postman
    When I submit a PendingReturn without pickupInfo
    Then I can see pendingTransId
    When I go to SQL Developer
    And Then I perform a Select on the pendingTransID in PICKUP_INFO table
    Then I can see pendingTransID is not in the table

  Scenario: QE to verify CARRIER_INFO table created with SCHED_DELIVERY_DATE as nullable
    Given I am in SQL Developer
    When I go to Columns in the CARRIER_INFO table
    Then I can see SCHED_DELIVERY_DATE can be nullable

  Scenario: QE to verify CARRIER_INFO table defined without tracking_nbr index
    Given I am in SQL Developer
    When I go to CARRIER_INFO table
    Then I can see CARRIER_INFO table is defined without tracking_nbr index

   Scenario: QE to verify pendingTransId is generated when a duplicate trackingNbr is used in carrierInfo
     Given I am in Postman
     When I submit a PendingReturn with a duplicate trackingNbr
     Then I can see pendingTransId
     When I go to SQL Developer
     And I perform a Select on the pendingTransID in CARRIER_INFO table
     Then I can see pendingTransID in column PT_ID
     And I can see SCHED_DELIVERY_DATE is null
     When I go to GEMS
     Then I can see Pending ID generated by DCR and posted to the topic

  Scenario: QE to verify carrierInfo is stored in CARRIER_INFO table when schedDeliveryDate null
    Given I am in Postman
    When I submit a PendingReturn with carrierInfo and null schedDeliveryDate
    Then I can see pendingTransId
    When I go to SQL Developer
    And I perform a Select on the TRACKING_NBR in CARRIER_INFO table
    Then I can see a row for each PT_ID that has the same TRACKING_NBR
