# Author: Stat Team
# Story: SPR-238  - PR - MSA Create
# Date Created: 11/15/2017
# Date Signed Off:

@STAT @Manual @pending_returns @SPR-238
Feature: As an application I want to provide a unique application id in the PT ID to Pending Returns created
  by MSA (via Site services) so as a business I can distinguish between Pending Returns initiated online
  by a customer and Pending Returns initiated by an agent using MSA
@Macy's
   Scenario: QE to verify pendingTransId is generated with X-Macys-ClientId = 01
    Given I am in Postman
    When I submit a PendingReturn with X-Macys-ClientId = 01
    Then I can see pendingTransId
    And  I can see application code = 01
    When I go to GEMS
    Then I can see Pending ID generated by DCR and posted to the topic

  Scenario: QE to verify pendingTransId is generated with X-Macys-ClientId = 02
    Given I am in Postman
    When I submit a PendingReturn with X-Macys-ClientId = 02
    Then I can see pendingTransIdg
    And  I can see application code = 02
    When I go to GEMS
    Then  I can see Pending ID generated by DCR and posted to the topic

  Scenario: QE to verify pendingTransId is generated with X-Macys-ClientId = 03
    Given I am in Postman
    When I submit a PendingReturn with X-Macys-ClientId = 03
    Then I can see pendingTransId
    And  I can see application code = 03
    When I go to GEMS
    Then  I can see Pending ID generated by DCR and posted to the topic

